#!/bin/bash

i3lock \
  --blur 5 \
  --bar-indicator \
  --bar-pos y+h \
  --bar-direction 1 \
  --bar-max-height 50 \
  --bar-base-width 50 \
  --bar-color 03045Ecc \
  --keyhl-color 023E8Acc \
  --bar-periodic-step 50 \
  --bar-step 50 \
  --redraw-thread \
  \
  --clock \
  --force-clock \
  --time-pos x+5:y+h-80 \
  --time-color 03045Ecc \
  --date-pos tx:ty+15 \
  --date-color 03045Ecc \
  --date-align 1 \
  --time-align 1 \
  --ringver-color 48CAE4cc \
  --ringwrong-color 023E8Acc \
  --status-pos x+5:y+h-16 \
  --verif-align 1 \
  --wrong-align 1 \
  --verif-color ffffffff \
  --wrong-color ffffffff \
  --modif-pos -50:-50